// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version v0.3.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/discord-gophers/goapi-gen/runtime"
	openapi_types "github.com/discord-gophers/goapi-gen/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AtualizarClienteTipoCliente.
var (
	UnknownAtualizarClienteTipoCliente = AtualizarClienteTipoCliente{}

	AtualizarClienteTipoClienteAvulso = AtualizarClienteTipoCliente{"avulso"}

	AtualizarClienteTipoClienteContrato = AtualizarClienteTipoCliente{"contrato"}
)

// Defines values for AtualizarFormularioNivelDificuldade.
var (
	UnknownAtualizarFormularioNivelDificuldade = AtualizarFormularioNivelDificuldade{}

	AtualizarFormularioNivelDificuldadeHigh = AtualizarFormularioNivelDificuldade{"high"}

	AtualizarFormularioNivelDificuldadeLow = AtualizarFormularioNivelDificuldade{"low"}

	AtualizarFormularioNivelDificuldadeMedium = AtualizarFormularioNivelDificuldade{"medium"}
)

// Defines values for ClienteTipoCliente.
var (
	UnknownClienteTipoCliente = ClienteTipoCliente{}

	ClienteTipoClienteAvulso = ClienteTipoCliente{"avulso"}

	ClienteTipoClienteContrato = ClienteTipoCliente{"contrato"}
)

// Defines values for CriarClienteTipoCliente.
var (
	UnknownCriarClienteTipoCliente = CriarClienteTipoCliente{}

	CriarClienteTipoClienteAvulso = CriarClienteTipoCliente{"avulso"}

	CriarClienteTipoClienteContrato = CriarClienteTipoCliente{"contrato"}
)

// Defines values for CriarFormularioNivelDificuldade.
var (
	UnknownCriarFormularioNivelDificuldade = CriarFormularioNivelDificuldade{}

	CriarFormularioNivelDificuldadeHigh = CriarFormularioNivelDificuldade{"high"}

	CriarFormularioNivelDificuldadeLow = CriarFormularioNivelDificuldade{"low"}

	CriarFormularioNivelDificuldadeMedium = CriarFormularioNivelDificuldade{"medium"}
)

// Defines values for CriarUsuarioCargo.
var (
	UnknownCriarUsuarioCargo = CriarUsuarioCargo{}

	CriarUsuarioCargoAdministrador = CriarUsuarioCargo{"administrador"}

	CriarUsuarioCargoTecnicoExterno = CriarUsuarioCargo{"tecnico_externo"}

	CriarUsuarioCargoTecnicoInterno = CriarUsuarioCargo{"tecnico_interno"}
)

// Defines values for FormularioNivelDificuldade.
var (
	UnknownFormularioNivelDificuldade = FormularioNivelDificuldade{}

	FormularioNivelDificuldadeHigh = FormularioNivelDificuldade{"high"}

	FormularioNivelDificuldadeLow = FormularioNivelDificuldade{"low"}

	FormularioNivelDificuldadeMedium = FormularioNivelDificuldade{"medium"}
)

// AtualizarCliente defines model for AtualizarCliente.
type AtualizarCliente struct {
	// CPF ou CNPJ (com ou sem máscara)
	CnpjOuCpf string `json:"cnpj_ou_cpf" validate:"required,cpf_cnpj"`

	// Email de contato
	EmailContato openapi_types.Email `json:"email_contato" validate:"omitempty,email"`
	Endereco     Endereco            `json:"endereco"`
	NomeCliente  string              `json:"nome_cliente" validate:"required,min=2,max=500"`
	NomeContato  string              `json:"nome_contato" validate:"required,min=2,max=500"`

	// Telefone de contato no formato E.164 (ex: +5511912345678)
	TelefoneContato string                      `json:"telefone_contato" validate:"omitempty,e164"`
	TipoCliente     AtualizarClienteTipoCliente `json:"tipo_cliente" validate:"required,oneof=avulso contrato"`
}

// AtualizarFormulario defines model for AtualizarFormulario.
type AtualizarFormulario struct {
	DataOcorrencia      time.Time                           `json:"data_ocorrencia" validate:"required"`
	DescricaoDefeito    string                              `json:"descricao_defeito" validate:"required,min=2,max=500"`
	DescricaoSolucao    string                              `json:"descricao_solucao" validate:"required,min=2,max=500"`
	NivelDificuldade    AtualizarFormularioNivelDificuldade `json:"nivel_dificuldade" validate:"required,oneof=low medium high"`
	Solicitante         string                              `json:"solicitante" validate:"required,min=2,max=500"`
	TecnicosResponsavel []string                            `json:"tecnicos_responsavel" validate:"required,min=1,dive,uuid"`
}

// AtualizarUsuario defines model for AtualizarUsuario.
type AtualizarUsuario struct {
	// Email de contato
	Email *openapi_types.Email `json:"email,omitempty" validate:"omitempty,email"`
	Nome  *string              `json:"nome,omitempty" validate:"omitempty,min=2,max=500"`
}

// BuscaCliente defines model for BuscaCliente.
type BuscaCliente struct {
	Cliente *Cliente `json:"cliente,omitempty"`
}

// BuscaFormulario defines model for BuscaFormulario.
type BuscaFormulario struct {
	Formulario Formulario `json:"formulario"`
}

// BuscaUsuario defines model for BuscaUsuario.
type BuscaUsuario struct {
	Usuario *Usuario `json:"usuario,omitempty"`
}

// Cliente defines model for Cliente.
type Cliente struct {
	// CPF ou CNPJ (com ou sem máscara)
	CnpjOuCpf string    `json:"cnpj_ou_cpf" validate:"required,min=11,max=18"`
	CreatedAt time.Time `json:"created_at" validate:"required"`

	// Email de contato
	EmailContato openapi_types.Email `json:"email_contato" validate:"omitempty,email"`
	Endereco     Endereco            `json:"endereco"`
	ID           string              `json:"id" validate:"required,uuid"`
	NomeCliente  string              `json:"nome_cliente" validate:"required,min=2,max=500"`
	NomeContato  string              `json:"nome_contato" validate:"required,min=2,max=500"`

	// Telefone de contato no formato E.164 (ex: +5511912345678)
	TelefoneContato string             `json:"telefone_contato" validate:"omitempty,e164"`
	TipoCliente     ClienteTipoCliente `json:"tipo_cliente" validate:"required,oneof=avulso contrato"`
	UpdatedAt       time.Time          `json:"updated_at" validate:"required"`
}

// CriarCliente defines model for CriarCliente.
type CriarCliente struct {
	// CPF ou CNPJ (com ou sem máscara)
	CnpjOuCpf string `json:"cnpj_ou_cpf" validate:"required,cpf_cnpj"`

	// Email de contato
	EmailContato openapi_types.Email `json:"email_contato" validate:"omitempty,email"`
	Endereco     Endereco            `json:"endereco"`
	NomeCliente  string              `json:"nome_cliente" validate:"required,min=2,max=500"`
	NomeContato  string              `json:"nome_contato" validate:"required,min=2,max=500"`

	// Telefone de contato no formato E.164 (ex: +5511912345678)
	TelefoneContato string                  `json:"telefone_contato" validate:"omitempty,e164"`
	TipoCliente     CriarClienteTipoCliente `json:"tipo_cliente" validate:"required,oneof=avulso contrato"`
}

// CriarFormulario defines model for CriarFormulario.
type CriarFormulario struct {
	ClienteID        string    `json:"cliente_id" validate:"required,uuid"`
	DataOcorrencia   time.Time `json:"data_ocorrencia" validate:"required"`
	DescricaoDefeito string    `json:"descricao_defeito" validate:"required,min=2,max=500"`
	DescricaoSolucao string    `json:"descricao_solucao" validate:"required,min=2,max=500"`

	// Nível de dificuldade
	NivelDificuldade    CriarFormularioNivelDificuldade `json:"nivel_dificuldade" validate:"required,oneof=low medium high"`
	Solicitante         string                          `json:"solicitante" validate:"required,min=2,max=500"`
	TecnicosResponsavel []string                        `json:"tecnicos_responsavel" validate:"required,min=1,dive,uuid"`
}

// CriarUsuario defines model for CriarUsuario.
type CriarUsuario struct {
	Cargo CriarUsuarioCargo `json:"cargo" validate:"required,oneof=tecnico_interno tecnico_externo administrador"`

	// Email de contato
	Email openapi_types.Email `json:"email" validate:"omitempty,email"`
	Nome  string              `json:"nome" validate:"required,min=2,max=500"`

	// Senha do usuário
	Password string `json:"password" validate:"required,min=8,max=64"`
}

// Endereco defines model for Endereco.
type Endereco struct {
	// Bairro da residência
	Bairro string `json:"bairro" validate:"required,min=2,max=500"`

	// CEP brasileiro
	Cep string `json:"cep" validate:"required,min=8,max=9"`

	// Cidade da residencia
	Cidade string `json:"cidade" validate:"required,min=2,max=500"`

	// Complemento do endereço (opcional)
	Complement string `json:"complement" validate:"omitempty,max=100"`

	// UF do estado da residencia
	Estado string `json:"estado" validate:"required,min=2,max=2"`

	// Latitude geográfica (opcional)
	Latitude float64 `json:"latitude" validate:"omitempty,gte=-90,lte=90"`

	// Longitude geográfica (opcional)
	Longitude float64 `json:"longitude" validate:"omitempty,gte=-180,lte=180"`

	// Número da residência
	Numero string `json:"numero" validate:"required,min=1,max=10"`

	// UF do pais da residencia
	Pais string `json:"pais" validate:"required,min=2,max=2"`

	// Rua da residência
	Rua string `json:"rua" validate:"required,min=2,max=500"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// Formulario defines model for Formulario.
type Formulario struct {
	CreatedAt           time.Time                  `json:"created_at" validate:"required"`
	DataOcorrencia      time.Time                  `json:"data_ocorrencia" validate:"required"`
	DescricaoDefeito    string                     `json:"descricao_defeito" validate:"required,min=2,max=500"`
	DescricaoSolucao    string                     `json:"descricao_solucao" validate:"required,min=2,max=500"`
	ID                  string                     `json:"id" validate:"required,uuid"`
	NivelDificuldade    FormularioNivelDificuldade `json:"nivel_dificuldade" validate:"required,oneof=low medium high"`
	Solicitante         string                     `json:"solicitante" validate:"required,min=2,max=500"`
	TecnicosResponsavel []Tecnico                  `json:"tecnicos_responsavel" validate:"required,min=1,dive,uuid"`
	UpdatedAt           time.Time                  `json:"updated_at" validate:"required"`
}

// ListaClientes defines model for ListaClientes.
type ListaClientes struct {
	Clientes []Cliente `json:"clientes"`
}

// ListaFormulario defines model for ListaFormulario.
type ListaFormulario struct {
	Formularios []Formulario `json:"formularios"`
}

// ListaUsuarios defines model for ListaUsuarios.
type ListaUsuarios struct {
	Usuarios []Usuario `json:"usuarios"`
}

// LoginReq defines model for LoginReq.
type LoginReq struct {
	// Email de contato
	Email openapi_types.Email `json:"email" validate:"required,email"`

	// Senha do usuário
	Password string `json:"password" validate:"required,min=8,max=64"`
}

// LoginRes defines model for LoginRes.
type LoginRes struct {
	// JWT de acesso
	AccessToken string `json:"access_token"`

	// Tempo de expiração em segundos
	ExpiresIn *int   `json:"expires_in,omitempty"`
	TokenType string `json:"token_type"`
}

// Resp200 defines model for Resp200.
type Resp200 struct {
	ID      string `json:"id" validate:"required,uuid"`
	Message string `json:"message" validate:"required"`
}

// Resp204 defines model for Resp204.
type Resp204 struct {
	Message string `json:"message" validate:"required"`
}

// Tecnico defines model for Tecnico.
type Tecnico struct {
	ID   string `json:"id" validate:"required,uuid"`
	Nome string `json:"nome" validate:"required,min=2,max=500"`
}

// Usuario defines model for Usuario.
type Usuario struct {
	Cargo     string    `json:"cargo" validate:"required"`
	CreatedAt time.Time `json:"created_at" validate:"required"`

	// Email de contato
	Email     openapi_types.Email `json:"email" validate:"omitempty,email"`
	ID        string              `json:"id" validate:"required,uuid"`
	Nome      string              `json:"nome" validate:"required,min=2,max=500"`
	UpdatedAt time.Time           `json:"updated_at" validate:"required"`
}

// AtualizarClienteTipoCliente defines model for AtualizarCliente.TipoCliente.
type AtualizarClienteTipoCliente struct {
	value string
}

func (t *AtualizarClienteTipoCliente) ToValue() string {
	return t.value
}
func (t AtualizarClienteTipoCliente) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *AtualizarClienteTipoCliente) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *AtualizarClienteTipoCliente) FromValue(value string) error {
	switch value {

	case AtualizarClienteTipoClienteAvulso.value:
		t.value = value
		return nil

	case AtualizarClienteTipoClienteContrato.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// AtualizarFormularioNivelDificuldade defines model for AtualizarFormulario.NivelDificuldade.
type AtualizarFormularioNivelDificuldade struct {
	value string
}

func (t *AtualizarFormularioNivelDificuldade) ToValue() string {
	return t.value
}
func (t AtualizarFormularioNivelDificuldade) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *AtualizarFormularioNivelDificuldade) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *AtualizarFormularioNivelDificuldade) FromValue(value string) error {
	switch value {

	case AtualizarFormularioNivelDificuldadeHigh.value:
		t.value = value
		return nil

	case AtualizarFormularioNivelDificuldadeLow.value:
		t.value = value
		return nil

	case AtualizarFormularioNivelDificuldadeMedium.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// ClienteTipoCliente defines model for Cliente.TipoCliente.
type ClienteTipoCliente struct {
	value string
}

func (t *ClienteTipoCliente) ToValue() string {
	return t.value
}
func (t ClienteTipoCliente) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *ClienteTipoCliente) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *ClienteTipoCliente) FromValue(value string) error {
	switch value {

	case ClienteTipoClienteAvulso.value:
		t.value = value
		return nil

	case ClienteTipoClienteContrato.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// CriarClienteTipoCliente defines model for CriarCliente.TipoCliente.
type CriarClienteTipoCliente struct {
	value string
}

func (t *CriarClienteTipoCliente) ToValue() string {
	return t.value
}
func (t CriarClienteTipoCliente) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *CriarClienteTipoCliente) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *CriarClienteTipoCliente) FromValue(value string) error {
	switch value {

	case CriarClienteTipoClienteAvulso.value:
		t.value = value
		return nil

	case CriarClienteTipoClienteContrato.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// Nível de dificuldade
type CriarFormularioNivelDificuldade struct {
	value string
}

func (t *CriarFormularioNivelDificuldade) ToValue() string {
	return t.value
}
func (t CriarFormularioNivelDificuldade) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *CriarFormularioNivelDificuldade) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *CriarFormularioNivelDificuldade) FromValue(value string) error {
	switch value {

	case CriarFormularioNivelDificuldadeHigh.value:
		t.value = value
		return nil

	case CriarFormularioNivelDificuldadeLow.value:
		t.value = value
		return nil

	case CriarFormularioNivelDificuldadeMedium.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// CriarUsuarioCargo defines model for CriarUsuario.Cargo.
type CriarUsuarioCargo struct {
	value string
}

func (t *CriarUsuarioCargo) ToValue() string {
	return t.value
}
func (t CriarUsuarioCargo) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *CriarUsuarioCargo) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *CriarUsuarioCargo) FromValue(value string) error {
	switch value {

	case CriarUsuarioCargoAdministrador.value:
		t.value = value
		return nil

	case CriarUsuarioCargoTecnicoExterno.value:
		t.value = value
		return nil

	case CriarUsuarioCargoTecnicoInterno.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// FormularioNivelDificuldade defines model for Formulario.NivelDificuldade.
type FormularioNivelDificuldade struct {
	value string
}

func (t *FormularioNivelDificuldade) ToValue() string {
	return t.value
}
func (t FormularioNivelDificuldade) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.value)
}
func (t *FormularioNivelDificuldade) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return t.FromValue(value)
}
func (t *FormularioNivelDificuldade) FromValue(value string) error {
	switch value {

	case FormularioNivelDificuldadeHigh.value:
		t.value = value
		return nil

	case FormularioNivelDificuldadeLow.value:
		t.value = value
		return nil

	case FormularioNivelDificuldadeMedium.value:
		t.value = value
		return nil

	}
	return fmt.Errorf("unknown enum value: %v", value)
}

// PostCreateClientJSONBody defines parameters for PostCreateClient.
type PostCreateClientJSONBody CriarCliente

// PutClientJSONBody defines parameters for PutClient.
type PutClientJSONBody AtualizarCliente

// PostCreateFormJSONBody defines parameters for PostCreateForm.
type PostCreateFormJSONBody CriarFormulario

// PutFormJSONBody defines parameters for PutForm.
type PutFormJSONBody AtualizarFormulario

// PostCreateUserJSONBody defines parameters for PostCreateUser.
type PostCreateUserJSONBody CriarUsuario

// PostLoginUserJSONBody defines parameters for PostLoginUser.
type PostLoginUserJSONBody LoginReq

// PutUpdateUserJSONBody defines parameters for PutUpdateUser.
type PutUpdateUserJSONBody AtualizarUsuario

// PostCreateClientJSONRequestBody defines body for PostCreateClient for application/json ContentType.
type PostCreateClientJSONRequestBody PostCreateClientJSONBody

// Bind implements render.Binder.
func (PostCreateClientJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PutClientJSONRequestBody defines body for PutClient for application/json ContentType.
type PutClientJSONRequestBody PutClientJSONBody

// Bind implements render.Binder.
func (PutClientJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PostCreateFormJSONRequestBody defines body for PostCreateForm for application/json ContentType.
type PostCreateFormJSONRequestBody PostCreateFormJSONBody

// Bind implements render.Binder.
func (PostCreateFormJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PutFormJSONRequestBody defines body for PutForm for application/json ContentType.
type PutFormJSONRequestBody PutFormJSONBody

// Bind implements render.Binder.
func (PutFormJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PostCreateUserJSONRequestBody defines body for PostCreateUser for application/json ContentType.
type PostCreateUserJSONRequestBody PostCreateUserJSONBody

// Bind implements render.Binder.
func (PostCreateUserJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PostLoginUserJSONRequestBody defines body for PostLoginUser for application/json ContentType.
type PostLoginUserJSONRequestBody PostLoginUserJSONBody

// Bind implements render.Binder.
func (PostLoginUserJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// PutUpdateUserJSONRequestBody defines body for PutUpdateUser for application/json ContentType.
type PutUpdateUserJSONRequestBody PutUpdateUserJSONBody

// Bind implements render.Binder.
func (PutUpdateUserJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
// It may also be instantiated directly, for the purpose of responding with a single status code.
type Response struct {
	body        interface{}
	Code        int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.Code)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(code int) *Response {
	resp.Code = code
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// PostCreateClientJSON200Response is a constructor method for a PostCreateClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateClientJSON200Response(body Resp200) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// PostCreateClientJSON400Response is a constructor method for a PostCreateClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateClientJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PostCreateClientJSON500Response is a constructor method for a PostCreateClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateClientJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// DeleteClientJSON204Response is a constructor method for a DeleteClient response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteClientJSON204Response(body Resp204) *Response {
	return &Response{
		body:        body,
		Code:        204,
		contentType: "application/json",
	}
}

// DeleteClientJSON400Response is a constructor method for a DeleteClient response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteClientJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// DeleteClientJSON401Response is a constructor method for a DeleteClient response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteClientJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// DeleteClientJSON500Response is a constructor method for a DeleteClient response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteClientJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetV1clientsListJSON200Response is a constructor method for a GetV1clientsList response.
// A *Response is returned with the configured status code and content type from the spec.
func GetV1clientsListJSON200Response(body ListaClientes) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetV1clientsListJSON500Response is a constructor method for a GetV1clientsList response.
// A *Response is returned with the configured status code and content type from the spec.
func GetV1clientsListJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// PutClientJSON204Response is a constructor method for a PutClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PutClientJSON204Response(body Resp204) *Response {
	return &Response{
		body:        body,
		Code:        204,
		contentType: "application/json",
	}
}

// PutClientJSON400Response is a constructor method for a PutClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PutClientJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PutClientJSON401Response is a constructor method for a PutClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PutClientJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// PutClientJSON500Response is a constructor method for a PutClient response.
// A *Response is returned with the configured status code and content type from the spec.
func PutClientJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetByIDClientJSON200Response is a constructor method for a GetByIDClient response.
// A *Response is returned with the configured status code and content type from the spec.
func GetByIDClientJSON200Response(body BuscaCliente) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetByIDClientJSON400Response is a constructor method for a GetByIDClient response.
// A *Response is returned with the configured status code and content type from the spec.
func GetByIDClientJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetByIDClientJSON401Response is a constructor method for a GetByIDClient response.
// A *Response is returned with the configured status code and content type from the spec.
func GetByIDClientJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// GetByIDClientJSON500Response is a constructor method for a GetByIDClient response.
// A *Response is returned with the configured status code and content type from the spec.
func GetByIDClientJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// PostCreateFormJSON201Response is a constructor method for a PostCreateForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateFormJSON201Response(body Resp200) *Response {
	return &Response{
		body:        body,
		Code:        201,
		contentType: "application/json",
	}
}

// PostCreateFormJSON400Response is a constructor method for a PostCreateForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateFormJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PostCreateFormJSON500Response is a constructor method for a PostCreateForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateFormJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// DeleteFormJSON204Response is a constructor method for a DeleteForm response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteFormJSON204Response(body Resp204) *Response {
	return &Response{
		body:        body,
		Code:        204,
		contentType: "application/json",
	}
}

// DeleteFormJSON400Response is a constructor method for a DeleteForm response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteFormJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// DeleteFormJSON500Response is a constructor method for a DeleteForm response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteFormJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// ListFormsJSON200Response is a constructor method for a ListForms response.
// A *Response is returned with the configured status code and content type from the spec.
func ListFormsJSON200Response(body ListaFormulario) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ListFormsJSON401Response is a constructor method for a ListForms response.
// A *Response is returned with the configured status code and content type from the spec.
func ListFormsJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// ListFormsJSON500Response is a constructor method for a ListForms response.
// A *Response is returned with the configured status code and content type from the spec.
func ListFormsJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// PutFormJSON204Response is a constructor method for a PutForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PutFormJSON204Response(body Resp204) *Response {
	return &Response{
		body:        body,
		Code:        204,
		contentType: "application/json",
	}
}

// PutFormJSON400Response is a constructor method for a PutForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PutFormJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PutFormJSON401Response is a constructor method for a PutForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PutFormJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// PutFormJSON500Response is a constructor method for a PutForm response.
// A *Response is returned with the configured status code and content type from the spec.
func PutFormJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetFormByIDJSON200Response is a constructor method for a GetFormByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetFormByIDJSON200Response(body BuscaFormulario) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetFormByIDJSON400Response is a constructor method for a GetFormByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetFormByIDJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetFormByIDJSON401Response is a constructor method for a GetFormByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetFormByIDJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// GetFormByIDJSON500Response is a constructor method for a GetFormByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetFormByIDJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// ListMembersJSON200Response is a constructor method for a ListMembers response.
// A *Response is returned with the configured status code and content type from the spec.
func ListMembersJSON200Response(body ListaUsuarios) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// ListMembersJSON400Response is a constructor method for a ListMembers response.
// A *Response is returned with the configured status code and content type from the spec.
func ListMembersJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// ListMembersJSON401Response is a constructor method for a ListMembers response.
// A *Response is returned with the configured status code and content type from the spec.
func ListMembersJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// ListMembersJSON404Response is a constructor method for a ListMembers response.
// A *Response is returned with the configured status code and content type from the spec.
func ListMembersJSON404Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// ListMembersJSON500Response is a constructor method for a ListMembers response.
// A *Response is returned with the configured status code and content type from the spec.
func ListMembersJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// PostCreateUserJSON200Response is a constructor method for a PostCreateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateUserJSON200Response(body Resp200) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// PostCreateUserJSON400Response is a constructor method for a PostCreateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateUserJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PostCreateUserJSON422Response is a constructor method for a PostCreateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateUserJSON422Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        422,
		contentType: "application/json",
	}
}

// PostCreateUserJSON500Response is a constructor method for a PostCreateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostCreateUserJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// DeleteUserAccountJSON204Response is a constructor method for a DeleteUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteUserAccountJSON204Response(body Resp204) *Response {
	return &Response{
		body:        body,
		Code:        204,
		contentType: "application/json",
	}
}

// DeleteUserAccountJSON400Response is a constructor method for a DeleteUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteUserAccountJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// DeleteUserAccountJSON401Response is a constructor method for a DeleteUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteUserAccountJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// DeleteUserAccountJSON404Response is a constructor method for a DeleteUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteUserAccountJSON404Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// DeleteUserAccountJSON500Response is a constructor method for a DeleteUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func DeleteUserAccountJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetUserAccountJSON200Response is a constructor method for a GetUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserAccountJSON200Response(body BuscaUsuario) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetUserAccountJSON400Response is a constructor method for a GetUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserAccountJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetUserAccountJSON401Response is a constructor method for a GetUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserAccountJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// GetUserAccountJSON404Response is a constructor method for a GetUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserAccountJSON404Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetUserAccountJSON500Response is a constructor method for a GetUserAccount response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserAccountJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// PostLoginUserJSON200Response is a constructor method for a PostLoginUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostLoginUserJSON200Response(body LoginRes) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// PostLoginUserJSON400Response is a constructor method for a PostLoginUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostLoginUserJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PostLoginUserJSON500Response is a constructor method for a PostLoginUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PostLoginUserJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// PutUpdateUserJSON204Response is a constructor method for a PutUpdateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PutUpdateUserJSON204Response(body Resp204) *Response {
	return &Response{
		body:        body,
		Code:        204,
		contentType: "application/json",
	}
}

// PutUpdateUserJSON400Response is a constructor method for a PutUpdateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PutUpdateUserJSON400Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// PutUpdateUserJSON401Response is a constructor method for a PutUpdateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PutUpdateUserJSON401Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        401,
		contentType: "application/json",
	}
}

// PutUpdateUserJSON404Response is a constructor method for a PutUpdateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PutUpdateUserJSON404Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// PutUpdateUserJSON500Response is a constructor method for a PutUpdateUser response.
// A *Response is returned with the configured status code and content type from the spec.
func PutUpdateUserJSON500Response(body ErrorResponse) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create client
	// (POST /v1/clients/create)
	PostCreateClient(w http.ResponseWriter, r *http.Request) *Response
	// Delete client
	// (DELETE /v1/clients/delete/{clientID})
	DeleteClient(w http.ResponseWriter, r *http.Request, clientID string) *Response
	// Get all clients
	// (GET /v1/clients/list)
	GetV1clientsList(w http.ResponseWriter, r *http.Request) *Response
	// Update client
	// (PUT /v1/clients/update/{clientID})
	PutClient(w http.ResponseWriter, r *http.Request, clientID string) *Response
	// Get client by ID
	// (GET /v1/clients/{clientID})
	GetByIDClient(w http.ResponseWriter, r *http.Request, clientID string) *Response
	// Form client
	// (POST /v1/forms/create)
	PostCreateForm(w http.ResponseWriter, r *http.Request) *Response
	// Delete form
	// (DELETE /v1/forms/delete/{formID})
	DeleteForm(w http.ResponseWriter, r *http.Request, formID string) *Response
	// List forms
	// (GET /v1/forms/list)
	ListForms(w http.ResponseWriter, r *http.Request) *Response
	// Update form
	// (PUT /v1/forms/update/{formID})
	PutForm(w http.ResponseWriter, r *http.Request, formID string) *Response
	// Get forms
	// (GET /v1/forms/{formID})
	GetFormByID(w http.ResponseWriter, r *http.Request, formID string) *Response
	// Get members
	// (GET /v1/members/list)
	ListMembers(w http.ResponseWriter, r *http.Request) *Response
	// Create a new user
	// (POST /v1/users/create)
	PostCreateUser(w http.ResponseWriter, r *http.Request) *Response
	// Delete user
	// (DELETE /v1/users/delete)
	DeleteUserAccount(w http.ResponseWriter, r *http.Request) *Response
	// Get user
	// (GET /v1/users/details)
	GetUserAccount(w http.ResponseWriter, r *http.Request) *Response
	// Login user
	// (POST /v1/users/login)
	PostLoginUser(w http.ResponseWriter, r *http.Request) *Response
	// Update user
	// (PUT /v1/users/update)
	PutUpdateUser(w http.ResponseWriter, r *http.Request) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// PostCreateClient operation middleware
func (siw *ServerInterfaceWrapper) PostCreateClient(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PostCreateClient(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeleteClient operation middleware
func (siw *ServerInterfaceWrapper) DeleteClient(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "clientID" -------------
	var clientID string

	if err := runtime.BindStyledParameter("simple", false, "clientID", chi.URLParam(r, "clientID"), &clientID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "clientID"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeleteClient(w, r, clientID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetV1clientsList operation middleware
func (siw *ServerInterfaceWrapper) GetV1clientsList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetV1clientsList(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PutClient operation middleware
func (siw *ServerInterfaceWrapper) PutClient(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "clientID" -------------
	var clientID string

	if err := runtime.BindStyledParameter("simple", false, "clientID", chi.URLParam(r, "clientID"), &clientID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "clientID"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PutClient(w, r, clientID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetByIDClient operation middleware
func (siw *ServerInterfaceWrapper) GetByIDClient(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "clientID" -------------
	var clientID string

	if err := runtime.BindStyledParameter("simple", false, "clientID", chi.URLParam(r, "clientID"), &clientID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "clientID"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetByIDClient(w, r, clientID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PostCreateForm operation middleware
func (siw *ServerInterfaceWrapper) PostCreateForm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PostCreateForm(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeleteForm operation middleware
func (siw *ServerInterfaceWrapper) DeleteForm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "formID" -------------
	var formID string

	if err := runtime.BindStyledParameter("simple", false, "formID", chi.URLParam(r, "formID"), &formID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "formID"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeleteForm(w, r, formID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// ListForms operation middleware
func (siw *ServerInterfaceWrapper) ListForms(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListForms(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PutForm operation middleware
func (siw *ServerInterfaceWrapper) PutForm(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "formID" -------------
	var formID string

	if err := runtime.BindStyledParameter("simple", false, "formID", chi.URLParam(r, "formID"), &formID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "formID"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PutForm(w, r, formID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetFormByID operation middleware
func (siw *ServerInterfaceWrapper) GetFormByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "formID" -------------
	var formID string

	if err := runtime.BindStyledParameter("simple", false, "formID", chi.URLParam(r, "formID"), &formID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "formID"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetFormByID(w, r, formID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListMembers(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PostCreateUser operation middleware
func (siw *ServerInterfaceWrapper) PostCreateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PostCreateUser(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeleteUserAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserAccount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeleteUserAccount(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetUserAccount operation middleware
func (siw *ServerInterfaceWrapper) GetUserAccount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetUserAccount(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PostLoginUser operation middleware
func (siw *ServerInterfaceWrapper) PostLoginUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PostLoginUser(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// PutUpdateUser operation middleware
func (siw *ServerInterfaceWrapper) PutUpdateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.PutUpdateUser(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:    "/",
		BaseRouter: chi.NewRouter(),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Post("/v1/clients/create", wrapper.PostCreateClient)
		r.Delete("/v1/clients/delete/{clientID}", wrapper.DeleteClient)
		r.Get("/v1/clients/list", wrapper.GetV1clientsList)
		r.Put("/v1/clients/update/{clientID}", wrapper.PutClient)
		r.Get("/v1/clients/{clientID}", wrapper.GetByIDClient)
		r.Post("/v1/forms/create", wrapper.PostCreateForm)
		r.Delete("/v1/forms/delete/{formID}", wrapper.DeleteForm)
		r.Get("/v1/forms/list", wrapper.ListForms)
		r.Put("/v1/forms/update/{formID}", wrapper.PutForm)
		r.Get("/v1/forms/{formID}", wrapper.GetFormByID)
		r.Get("/v1/members/list", wrapper.ListMembers)
		r.Post("/v1/users/create", wrapper.PostCreateUser)
		r.Delete("/v1/users/delete", wrapper.DeleteUserAccount)
		r.Get("/v1/users/details", wrapper.GetUserAccount)
		r.Post("/v1/users/login", wrapper.PostLoginUser)
		r.Put("/v1/users/update", wrapper.PutUpdateUser)
	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc2W7bSLp+FYKnL5LTlE1qs2Qg6JM4C5yTSRtZugdjp4USWaJKIllULdoMPUxjLhoY",
	"YF5gbv1ig6qiKJIiZcq21HZHV4lYRdZf//99/8air3Ub+yEOYMCofnqtU7sPfSD/+5Jx4KE5IGceggGD",
	"4lpIcAgJQ1DOsINw0MG8Y4c98dOB1CYoZAgH+ql+dvFWw1w7+3jxXntmY1/8oNDX/JvfqQ0IeK4bOpwC",
	"P/Sgfqpb1aNavXHUPGkdm6ZpVdqmbug+mH6Agcv6+qnVMnQfBfFPy9DZLBR3UkZQ4OqGPq24uAKnjIAK",
	"A64UcAw85AAhuk7giCMCHcMOex0huL5YGDr0AfI6Ng4YYHh9D2/EsOZAbTkjKXJ07f9oCAni/lEAmW7o",
	"PUx8wPRT9ej0JqqN+rZiYx8x6IdsZqjnSaEDBxJoS3l/ILCnn+r/c7wy43Fkw+M3y3kLQw+wDzv2ypAJ",
	"qRqmmdJt9c6q9VHwomr4YPqiYZpSVLXsSr17WpZBD/ZwAIst+yWakTCuFmBNWQ9rb46sZl17Bqen2o+N",
	"hmW1rWqt3mietNKoTY9lENtMI9Y09BAwBolY/rerqx8vrUr729WVc20ZVn3xg34PaFjNuto3CnHSyjDg",
	"vn56qYMx96hAr9gqEQr5dmdt4wDi3gv1RC1+3kIsv5wjlkwBLiOZkfIcCUBnCZljyQymVvvA3QG0mdwH",
	"ZTj0kNtnYg/I0U9103dpa+KDenVi+VJVsXd7i4nPPUAQXndwDmCgg21MCAxsBMSlmN9CLxWGfKjfVZVS",
	"DgVLG+COA3sQ7ZUmq7Up9rgN9rl2gMbQ6zioh2zuOcBJ4dXDE0Em6CDu64beR27/3oj18ERTT9Tk84QQ",
	"FHvIRgzs1ykyaAfIxrRDIA1xQMEYehKpDPo0hTHOkbMGr4UU7FxNXsVBQAiYbSeWZThoDA25yhqB14Fp",
	"rPEhz4xpreaBrEADJamMZiczt9eoTk9Mn6Wp/JXyfB6r2PlEwrvwbw+NxtU6WTguymk9oC3SqzoU11mj",
	"IcV8xakNilPD1cCmFGV5f1kxWrDWcusjEzmMmCsxNvnwXmpskzCJp2TJkHhISZi2q5T3HdQec3MIVpIW",
	"QpSvBjbJuLy/rMImczOwu4N5w+eWsttfK5uXbsySeLZacn82gYBBpwPYLsL1d1MwCPTcFolKWymKMIcy",
	"5FCG7LoMMXQeOjtzAJmwIDmxVaWzZXmTqo0Sni21y5IRyauZc9Q9aTvVOnFVKCDo0N05dHcObvXgVp90",
	"d4eMxuOwzromrjX4yrNtqgoiYTu7SXMOfaP99o3S7P948+8xlI493Ze4pbu0In48dGg47bHhlKCk8Wi7",
	"T70QsCofMOQOvNrK1RSW9TYgLk4662jxDgpEsEiI04HT5RXg+ChAlBHgYHJvZ55ZUcusp6VXi/Om77ld",
	"toFLIaB0gomzrp7PMOgDzcEap/zmd4GGxP7j21IqaNZTcrZSScSzn14c/e/ly8o/QGX+7bn8dXXlqP9c",
	"/qauX105354fXbeM5l1yjNQ2W3KbMtXIEHNpO6lpI4J0QhNlO2KzMJiNB71a32IKZ28SqW6aNl2ACMlJ",
	"7F7J65oDNAIpcm7+FTmCPRnfhmFOKfTmQusSQJEHEUmTwrRqllmxzEy5095gdZEyNhaVn8S/tYexaVvJ",
	"jvKj5Zm8HqsU7lmjWKjKhwHLkSwew4JWKo+8+QNrz3BoIxwA73kmKReC3rkxDqYvrEgqSBlwcuD39a0U",
	"RI6uaWxl9s8XGU/34OqrSjE9wBDjeUb9EI1oLsQuufm9h2yQVtsqH8W860ElMPJFkGorc6sflfZKpwH3",
	"u5BsoVOXwRfiAR6DL9pKtR4O3CKhl0N3ktpqpcSWP+8lt3iCENxqRZkn92GeT/p48x8xsO6Ukv2P2sss",
	"VNP14/0a4BF4owCFaBFyxdgG3L76tB/cEg7WJfzEwZ/k1zPhTkgXW9tYhqLYgcbeIVK1igopT5ZgZhLw",
	"JePkvNuw0Jjj6Ry1VNXwhhBMPqlkNadR50NKgSsHMol7ZmfLiSUFqY9mlDZJOEKQqncrGyvqnb53OVTU",
	"O1t7R296Duc7CsvtTW3dL+rmnRXd+38/svdSfos3JQtD/4AoW55joIWNQlragPGRhozNCtodtKw3ro2d",
	"oO864YDygUK3lLzc0Yfy4icPQdyyg+TjS27CPWn1+hNK2n231l5tImqf0MJjEeXljw9I3CJ8/OCyJwhR",
	"jdkT6p04fKx49AG7KPgER0/ouFHsF1btk++4n7FtA4NMB81qz5yNZifdSRICObgFtg0p7TA8hMG6at//",
	"+kXgAIg5aRjA2ft+952Nfkbvz7/Oz62P6JyeB58a9tl583wY/v2Xs/fto6OjvB4tnIaIQNpBQd4LMT/E",
	"Ykk5Cdz8cfNPrEFfo9DlgYNpUoZaM1FGo4BBFxJJJ7GXjrp+nawaICCyutqcfKY0knpa2ffXs7CHwRD4",
	"o5Oh4rNIiaumua793aQ0hXn2PQPklmn5kFS9Gjbtes/lNKGH+haVwd0lLhR2YejL3GVP9thr57fo5Eeu",
	"Im5/HXCPOmUPB9yeSu//L4CrP+e80vJdfKKdf8/TRdnuvqi+oM0JYrPPIjVT+Fex4iUXOrzWu/LX2+WO",
	"3//6RST9crZ+Go2udt9nLFQPRkFPkkjizhYyxCV0HPD6iGqIag62uQ8FPBEOtB4mGutD7WcPOZAOtZcX",
	"5yKUesiGUWclAHJtGe8QU93cCXBdSDS8ukk39DEkVC1VOzKPTHEDDmEAQhRfktlPX+77eGwdq4SfHitF",
	"S9+AaV7bW45rQFM36PLBRG7gXGj6AlOm5pwtJwgbQ8peYWe21EvUUQdh6CFb3nw8oDhYfeN3ax2TPBy2",
	"WKxpWA1pkbSflAR6Em+McCgBqBpXUhFRuH4QCZfhP084BWZhlfoDrphuxOWs+wo4sSoWht7Y59rn8v0u",
	"8LTPkIwh0eQNepKI+ullmoKX3xbfDJ1y3wdktoJeDDzlXC71s0StOq3Y2IEuDCoR6ipd7MwqEXFIjIPc",
	"FI6agz4fTNCoP5irPSSZ4UAPMnh8rX6fv14ocoiL6zR5La/HNNG6M+389RpZ1KyYKCEgwIcMEip1kYto",
	"+RSRREv6CoeptraUag3jRsKCt5ykEOrO8KH+wHyo52HjI9bOoiX+ZErUTWt/a38NAGd9TNBc+YKnxscI",
	"47fwcZ1ns153PrSHnBGLmOs885CKOy7MCT/vINOA50WL0jVGvYPsF0sJQD+gyOXvyMOne3M5Ov75/5+i",
	"WddVXNaw/VGjy8Kp13W6U3fdsCptyzjQkOdY+auceZv3vOBsf64z11U+fF6z9mcNinObSEnlc5uDLz/4",
	"8iLSR2DaWW5VH1W52XWANapNuuuuIe0Tij3/ZofwDrJXs/PXjzmfejhUpL5wLQw+3xMBnzL/BLoz2C4b",
	"dWF9wIIJnM+r3WCwopbA5hblfAAn8guUDQX9WzW8s3I+9YXzmpLF6Pb1vHWo5x8t5qVF1yLOSwYDB8lz",
	"lfeOOiNoj33g96zeuNXLUmNZz4tfZat5MXdjLR9xZGPkkfsuijtKmkMV/z0RIYJX5H6LibAOcOq3Zu3B",
	"qDkZMj7NArxUIS2nroFZlLZvo5Hd1s+bnf4yiTlk8qXBJLQaW3UbLFmNkUWIb1nAq5Eslpa1e8JZbq7c",
	"N3jKC84ejZvcYQVfIp05lPCHEv6hS/hbo8jd0ynQbg/roDUaOhbqZz1E0jVsKODl5OL6XdBC1PCPL4d6",
	"4Mq9XNw7UO/JVO93CbmTQd/x6+O2HQ7dRFfMh34XkpIJXDQ5N4X7Wzy22yQuPiF7gHISylpF+4g1YDM0",
	"hhqFVB7JkALV9ygQhUQLsAAoD54su1YoX/Jrie2il4xmu0EGNdccOtPailqcCmJt1RUTt2zoin1Vwzvr",
	"iq3+pl5B30kKqIkofjjfkuZ9tfrdtyCyh2dSkF5SSUD4/r02C077Hj5pemQOsoRLNtY2ttgklkOCe0h+",
	"P5vXYhPSvrRtzIOct/t7KZA+Cc9FsUagj8fIwZqNfY1ydV7+EOwOwe7+vcBihuaUZdNZs8v8JuhPk+fW",
	"lsxjAHl0YxopSbecmFOUbWTcA9dFG8LdIZM8kOv+meQ2zHJqs3HYGvp+c9BtZ5nlYVd9zJSfQ8qvrzRQ",
	"nD7KCTvMHuMvAItM6QAG9poyxh+kPUpyP7qUTSFoF7madUJwo8cbNdOdNrK4Vq3+2zr8G2PGBWdq2g7h",
	"vfZ39QthHgt56K4fotlfKJolmLi9g4juyvMOzKoG06lLWvOGLSu5EkLJTahGPSeefqofgxDpi4K4GjZb",
	"kLZ5zW1ZPVdfLP4bAAD//36/w+noawAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
