// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClientQuery = `-- name: CreateClientQuery :one
INSERT INTO clients (
  name,

  email,
  phone,
  contact_name,
  client_type,
  cnpj_cpf,

  postal_code,
  neighborhood,
  country,
  state,
  city,
  street,
  number,
  complement,
  latitude,
  longitude
   )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id
`

type CreateClientQueryParams struct {
	Name         string        `json:"name"`
	Email        pgtype.Text   `json:"email"`
	Phone        pgtype.Text   `json:"phone"`
	ContactName  pgtype.Text   `json:"contact_name"`
	ClientType   ClientType    `json:"client_type"`
	CnpjCpf      pgtype.Text   `json:"cnpj_cpf"`
	PostalCode   pgtype.Text   `json:"postal_code"`
	Neighborhood pgtype.Text   `json:"neighborhood"`
	Country      pgtype.Text   `json:"country"`
	State        pgtype.Text   `json:"state"`
	City         pgtype.Text   `json:"city"`
	Street       pgtype.Text   `json:"street"`
	Number       pgtype.Text   `json:"number"`
	Complement   pgtype.Text   `json:"complement"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) CreateClientQuery(ctx context.Context, arg CreateClientQueryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createClientQuery,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.ContactName,
		arg.ClientType,
		arg.CnpjCpf,
		arg.PostalCode,
		arg.Neighborhood,
		arg.Country,
		arg.State,
		arg.City,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Latitude,
		arg.Longitude,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteClientQuery = `-- name: DeleteClientQuery :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClientQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClientQuery, id)
	return err
}

const getAllClientsQuery = `-- name: GetAllClientsQuery :many
SELECT
  id,
  name,

  email,
  phone,
  contact_name,
  client_type,
  cnpj_cpf,

  postal_code,
  neighborhood,
  country,
  state,
  city,
  street,
  number,
  complement,
  latitude,
  longitude,

  created_at,
  updated_at
FROM clients
ORDER BY id DESC
`

type GetAllClientsQueryRow struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	Email        pgtype.Text   `json:"email"`
	Phone        pgtype.Text   `json:"phone"`
	ContactName  pgtype.Text   `json:"contact_name"`
	ClientType   ClientType    `json:"client_type"`
	CnpjCpf      pgtype.Text   `json:"cnpj_cpf"`
	PostalCode   pgtype.Text   `json:"postal_code"`
	Neighborhood pgtype.Text   `json:"neighborhood"`
	Country      pgtype.Text   `json:"country"`
	State        pgtype.Text   `json:"state"`
	City         pgtype.Text   `json:"city"`
	Street       pgtype.Text   `json:"street"`
	Number       pgtype.Text   `json:"number"`
	Complement   pgtype.Text   `json:"complement"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

func (q *Queries) GetAllClientsQuery(ctx context.Context) ([]GetAllClientsQueryRow, error) {
	rows, err := q.db.Query(ctx, getAllClientsQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllClientsQueryRow
	for rows.Next() {
		var i GetAllClientsQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.ContactName,
			&i.ClientType,
			&i.CnpjCpf,
			&i.PostalCode,
			&i.Neighborhood,
			&i.Country,
			&i.State,
			&i.City,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientByIdQuery = `-- name: GetClientByIdQuery :one
SELECT
  id,
  name,
  email,
  phone,
  contact_name,
  client_type,
  cnpj_cpf,

  postal_code,
  neighborhood,
  country,
  state,
  city,
  street,
  number,
  complement,
  latitude,
  longitude,

  created_at,
  updated_at
FROM clients
WHERE id = $1
`

type GetClientByIdQueryRow struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	Email        pgtype.Text   `json:"email"`
	Phone        pgtype.Text   `json:"phone"`
	ContactName  pgtype.Text   `json:"contact_name"`
	ClientType   ClientType    `json:"client_type"`
	CnpjCpf      pgtype.Text   `json:"cnpj_cpf"`
	PostalCode   pgtype.Text   `json:"postal_code"`
	Neighborhood pgtype.Text   `json:"neighborhood"`
	Country      pgtype.Text   `json:"country"`
	State        pgtype.Text   `json:"state"`
	City         pgtype.Text   `json:"city"`
	Street       pgtype.Text   `json:"street"`
	Number       pgtype.Text   `json:"number"`
	Complement   pgtype.Text   `json:"complement"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

func (q *Queries) GetClientByIdQuery(ctx context.Context, id uuid.UUID) (GetClientByIdQueryRow, error) {
	row := q.db.QueryRow(ctx, getClientByIdQuery, id)
	var i GetClientByIdQueryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ContactName,
		&i.ClientType,
		&i.CnpjCpf,
		&i.PostalCode,
		&i.Neighborhood,
		&i.Country,
		&i.State,
		&i.City,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientQuery = `-- name: UpdateClientQuery :exec
UPDATE clients
SET
  name = $1,

  email = $2,
  phone = $3,
  contact_name = $4,
  client_type = $5,
  cnpj_cpf = $6,
  postal_code = $7,
  neighborhood = $8,
  country = $9,
  state = $10,
  city = $11,
  street = $12,
  number = $13,
  complement = $14,
  latitude = $15,
  longitude = $16
WHERE id = $17
`

type UpdateClientQueryParams struct {
	Name         string        `json:"name"`
	Email        pgtype.Text   `json:"email"`
	Phone        pgtype.Text   `json:"phone"`
	ContactName  pgtype.Text   `json:"contact_name"`
	ClientType   ClientType    `json:"client_type"`
	CnpjCpf      pgtype.Text   `json:"cnpj_cpf"`
	PostalCode   pgtype.Text   `json:"postal_code"`
	Neighborhood pgtype.Text   `json:"neighborhood"`
	Country      pgtype.Text   `json:"country"`
	State        pgtype.Text   `json:"state"`
	City         pgtype.Text   `json:"city"`
	Street       pgtype.Text   `json:"street"`
	Number       pgtype.Text   `json:"number"`
	Complement   pgtype.Text   `json:"complement"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
	ID           uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateClientQuery(ctx context.Context, arg UpdateClientQueryParams) error {
	_, err := q.db.Exec(ctx, updateClientQuery,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.ContactName,
		arg.ClientType,
		arg.CnpjCpf,
		arg.PostalCode,
		arg.Neighborhood,
		arg.Country,
		arg.State,
		arg.City,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	return err
}
