// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package pgstore

import (
	"context"
)

// iteratorForCreateFormTecnicoQuery implements pgx.CopyFromSource.
type iteratorForCreateFormTecnicoQuery struct {
	rows                 []CreateFormTecnicoQueryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateFormTecnicoQuery) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateFormTecnicoQuery) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MemberID,
		r.rows[0].FormID,
	}, nil
}

func (r iteratorForCreateFormTecnicoQuery) Err() error {
	return nil
}

func (q *Queries) CreateFormTecnicoQuery(ctx context.Context, arg []CreateFormTecnicoQueryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"form_tecnico"}, []string{"member_id", "form_id"}, &iteratorForCreateFormTecnicoQuery{rows: arg})
}
