// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFormQuery = `-- name: CreateFormQuery :one
INSERT INTO forms (
    client_id,
    solicited_name,
    difficulty_level,
    defect_description,
    solution_description,
    occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateFormQueryParams struct {
	ClientID            uuid.UUID       `json:"client_id"`
	SolicitedName       string          `json:"solicited_name"`
	DifficultyLevel     DifficultyLevel `json:"difficulty_level"`
	DefectDescription   pgtype.Text     `json:"defect_description"`
	SolutionDescription pgtype.Text     `json:"solution_description"`
	OccurredAt          time.Time       `json:"occurred_at"`
}

func (q *Queries) CreateFormQuery(ctx context.Context, arg CreateFormQueryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createFormQuery,
		arg.ClientID,
		arg.SolicitedName,
		arg.DifficultyLevel,
		arg.DefectDescription,
		arg.SolutionDescription,
		arg.OccurredAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

type CreateFormTecnicoQueryParams struct {
	MemberID uuid.UUID `json:"member_id"`
	FormID   uuid.UUID `json:"form_id"`
}

const deleteFormQuery = `-- name: DeleteFormQuery :exec
DELETE FROM forms
WHERE id = $1
`

func (q *Queries) DeleteFormQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFormQuery, id)
	return err
}

const getFormByIdQuery = `-- name: GetFormByIdQuery :one
SELECT
    f.id,
    f.client_id,
    c.name as client_name,
    f.occurred_at,
    f.solicited_name,
    f.difficulty_level,
    f.defect_description,
    f.solution_description,
    f.created_at,
    f.updated_at
FROM forms f
JOIN clients c ON f.client_id = c.id
WHERE f.id = $1
`

type GetFormByIdQueryRow struct {
	ID                  uuid.UUID          `json:"id"`
	ClientID            uuid.UUID          `json:"client_id"`
	ClientName          string             `json:"client_name"`
	OccurredAt          time.Time          `json:"occurred_at"`
	SolicitedName       string             `json:"solicited_name"`
	DifficultyLevel     DifficultyLevel    `json:"difficulty_level"`
	DefectDescription   pgtype.Text        `json:"defect_description"`
	SolutionDescription pgtype.Text        `json:"solution_description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFormByIdQuery(ctx context.Context, id uuid.UUID) (GetFormByIdQueryRow, error) {
	row := q.db.QueryRow(ctx, getFormByIdQuery, id)
	var i GetFormByIdQueryRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.OccurredAt,
		&i.SolicitedName,
		&i.DifficultyLevel,
		&i.DefectDescription,
		&i.SolutionDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormTecnicosByFormID = `-- name: GetFormTecnicosByFormID :many
SELECT
    form_tecnico.id,
    form_tecnico.member_id,
    form_tecnico.form_id,
    form_tecnico.created_at,
    form_tecnico.updated_at,
    users.username AS user_name,
    users.email AS user_email
FROM form_tecnico
JOIN members ON form_tecnico.member_id = members.id
JOIN users ON members.user_id = users.id
WHERE form_tecnico.form_id = $1
ORDER BY form_tecnico.id ASC
`

type GetFormTecnicosByFormIDRow struct {
	ID        uuid.UUID          `json:"id"`
	MemberID  uuid.UUID          `json:"member_id"`
	FormID    uuid.UUID          `json:"form_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserName  string             `json:"user_name"`
	UserEmail string             `json:"user_email"`
}

func (q *Queries) GetFormTecnicosByFormID(ctx context.Context, formID uuid.UUID) ([]GetFormTecnicosByFormIDRow, error) {
	rows, err := q.db.Query(ctx, getFormTecnicosByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFormTecnicosByFormIDRow
	for rows.Next() {
		var i GetFormTecnicosByFormIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.FormID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFormsQuery = `-- name: GetFormsQuery :many
SELECT
    f.id,
    f.client_id,
    c.name as client_name,
    f.occurred_at,
    f.solicited_name,
    f.difficulty_level,
    f.defect_description,
    f.solution_description,
    f.created_at,
    f.updated_at
FROM forms f
JOIN clients c ON f.client_id = c.id
ORDER BY f.id ASC
`

type GetFormsQueryRow struct {
	ID                  uuid.UUID          `json:"id"`
	ClientID            uuid.UUID          `json:"client_id"`
	ClientName          string             `json:"client_name"`
	OccurredAt          time.Time          `json:"occurred_at"`
	SolicitedName       string             `json:"solicited_name"`
	DifficultyLevel     DifficultyLevel    `json:"difficulty_level"`
	DefectDescription   pgtype.Text        `json:"defect_description"`
	SolutionDescription pgtype.Text        `json:"solution_description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFormsQuery(ctx context.Context) ([]GetFormsQueryRow, error) {
	rows, err := q.db.Query(ctx, getFormsQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFormsQueryRow
	for rows.Next() {
		var i GetFormsQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.OccurredAt,
			&i.SolicitedName,
			&i.DifficultyLevel,
			&i.DefectDescription,
			&i.SolutionDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormQuery = `-- name: UpdateFormQuery :exec
UPDATE forms
SET client_id = $1,
    solicited_name = $2,
    difficulty_level = $3,
    defect_description = $4,
    solution_description = $5,
    updated_at = NOW()
WHERE id = $6
`

type UpdateFormQueryParams struct {
	ClientID            uuid.UUID       `json:"client_id"`
	SolicitedName       string          `json:"solicited_name"`
	DifficultyLevel     DifficultyLevel `json:"difficulty_level"`
	DefectDescription   pgtype.Text     `json:"defect_description"`
	SolutionDescription pgtype.Text     `json:"solution_description"`
	ID                  uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateFormQuery(ctx context.Context, arg UpdateFormQueryParams) error {
	_, err := q.db.Exec(ctx, updateFormQuery,
		arg.ClientID,
		arg.SolicitedName,
		arg.DifficultyLevel,
		arg.DefectDescription,
		arg.SolutionDescription,
		arg.ID,
	)
	return err
}
