// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createMemberQuery = `-- name: CreateMemberQuery :exec
INSERT INTO members (user_id, role)
VALUES ($1, $2)
`

type CreateMemberQueryParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Role   MemberRole `json:"role"`
}

func (q *Queries) CreateMemberQuery(ctx context.Context, arg CreateMemberQueryParams) error {
	_, err := q.db.Exec(ctx, createMemberQuery, arg.UserID, arg.Role)
	return err
}

const getMemberQuery = `-- name: GetMemberQuery :many
SELECT
    m.id,
    m.role,
    u.email,
    u.username
FROM members m
JOIN users u ON m.user_id = u.id
`

type GetMemberQueryRow struct {
	ID       uuid.UUID  `json:"id"`
	Role     MemberRole `json:"role"`
	Email    string     `json:"email"`
	Username string     `json:"username"`
}

func (q *Queries) GetMemberQuery(ctx context.Context) ([]GetMemberQueryRow, error) {
	rows, err := q.db.Query(ctx, getMemberQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberQueryRow
	for rows.Next() {
		var i GetMemberQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
