// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClientType string

const (
	ClientTypeAvulso   ClientType = "avulso"
	ClientTypeContrato ClientType = "contrato"
)

func (e *ClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientType(s)
	case string:
		*e = ClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientType: %T", src)
	}
	return nil
}

type NullClientType struct {
	ClientType ClientType `json:"client_type"`
	Valid      bool       `json:"valid"` // Valid is true if ClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientType) Scan(value interface{}) error {
	if value == nil {
		ns.ClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientType), nil
}

type DifficultyLevel string

const (
	DifficultyLevelLow    DifficultyLevel = "low"
	DifficultyLevelMedium DifficultyLevel = "medium"
	DifficultyLevelHigh   DifficultyLevel = "high"
)

func (e *DifficultyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DifficultyLevel(s)
	case string:
		*e = DifficultyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for DifficultyLevel: %T", src)
	}
	return nil
}

type NullDifficultyLevel struct {
	DifficultyLevel DifficultyLevel `json:"difficulty_level"`
	Valid           bool            `json:"valid"` // Valid is true if DifficultyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficultyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.DifficultyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DifficultyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficultyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DifficultyLevel), nil
}

type MemberRole string

const (
	MemberRoleTecnicoInterno MemberRole = "tecnico_interno"
	MemberRoleTecnicoExterno MemberRole = "tecnico_externo"
	MemberRoleAdministrador  MemberRole = "administrador"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

// Clientes do sistema (empresas e pessoas físicas) - avulso ou contrato
type Client struct {
	// Identificador único do cliente (UUID)
	ID uuid.UUID `json:"id"`
	// Nome/Razão social do cliente (mínimo 3 caracteres)
	Name string `json:"name"`
	// Tipo de cliente: avulso (serviços pontuais) ou contrato (recorrente)
	ClientType ClientType `json:"client_type"`
	// CNPJ (18 chars) ou CPF (14 chars com formatação)
	CnpjCpf pgtype.Text `json:"cnpj_cpf"`
	// E-mail do cliente (opcional, validado por regex)
	Email pgtype.Text `json:"email"`
	// Telefone de contato
	Phone pgtype.Text `json:"phone"`
	// Nome da pessoa de contato
	ContactName pgtype.Text `json:"contact_name"`
	// Logradouro (rua, avenida, etc)
	Street pgtype.Text `json:"street"`
	// Número do endereço
	Number pgtype.Text `json:"number"`
	// Bairro
	Neighborhood pgtype.Text `json:"neighborhood"`
	// Cidade
	City pgtype.Text `json:"city"`
	// UF (sigla do estado)
	State pgtype.Text `json:"state"`
	// Código do país (ISO 3166-1 alpha-2) - padrão BR
	Country pgtype.Text `json:"country"`
	// CEP do endereço
	PostalCode pgtype.Text `json:"postal_code"`
	// Complemento do endereço
	Complement pgtype.Text `json:"complement"`
	// Latitude para geolocalização (-90 a 90)
	Latitude pgtype.Float8 `json:"latitude"`
	// Longitude para geolocalização (-180 a 180)
	Longitude pgtype.Float8 `json:"longitude"`
	// Data e hora de criação do registro
	CreatedAt time.Time `json:"created_at"`
	// Data e hora da última atualização (trigger automático)
	UpdatedAt time.Time `json:"updated_at"`
}

type Form struct {
	ID                  uuid.UUID          `json:"id"`
	ClientID            uuid.UUID          `json:"client_id"`
	SolicitedName       string             `json:"solicited_name"`
	DifficultyLevel     DifficultyLevel    `json:"difficulty_level"`
	DefectDescription   pgtype.Text        `json:"defect_description"`
	SolutionDescription pgtype.Text        `json:"solution_description"`
	OccurredAt          time.Time          `json:"occurred_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FormTecnico struct {
	ID        uuid.UUID          `json:"id"`
	MemberID  uuid.UUID          `json:"member_id"`
	FormID    uuid.UUID          `json:"form_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Membros operacionais do sistema (técnicos, auxiliares, estagiários e admins)
type Member struct {
	// Identificador único do membro (UUID)
	ID uuid.UUID `json:"id"`
	// Referência ao usuário (relação 1:1 com users)
	UserID uuid.UUID `json:"user_id"`
	// Cargo/função do membro: admin, tecnico, auxiliar ou estagiario
	Role MemberRole `json:"role"`
	// Indica se o membro está ativo para atribuições
	IsActive bool `json:"is_active"`
	// Data e hora de criação do registro
	CreatedAt time.Time `json:"created_at"`
	// Data e hora da última atualização (trigger automático)
	UpdatedAt time.Time `json:"updated_at"`
}

// Usuários do sistema com credenciais de autenticação
type User struct {
	// Identificador único do usuário (UUID)
	ID uuid.UUID `json:"id"`
	// Nome de usuário único (mínimo 3 caracteres)
	Username string `json:"username"`
	// E-mail único do usuário (validado por regex)
	Email string `json:"email"`
	// Hash da senha (bcrypt/argon2)
	PasswordHash []byte `json:"password_hash"`
	// Data e hora de criação do registro
	CreatedAt time.Time `json:"created_at"`
	// Data e hora da última atualização (trigger automático)
	UpdatedAt time.Time `json:"updated_at"`
}
