// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserQuery = `-- name: CreateUserQuery :one
INSERT INTO users (username, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateUserQueryParams struct {
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUserQuery(ctx context.Context, arg CreateUserQueryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUserQuery,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUserQuery = `-- name: DeleteUserQuery :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserQuery, id)
	return err
}

const getUserByEmailQuery = `-- name: GetUserByEmailQuery :one
SELECT id, username, email, password_hash
FROM users
WHERE email = $1
`

type GetUserByEmailQueryRow struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
}

func (q *Queries) GetUserByEmailQuery(ctx context.Context, email string) (GetUserByEmailQueryRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailQuery, email)
	var i GetUserByEmailQueryRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByIdQuery = `-- name: GetUserByIdQuery :one
SELECT u.id, u.username, u.email, m.role, u.created_at, u.updated_at
FROM users u
JOIN members m ON u.id = m.user_id
WHERE u.id = $1
`

type GetUserByIdQueryRow struct {
	ID        uuid.UUID  `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Role      MemberRole `json:"role"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByIdQuery(ctx context.Context, id uuid.UUID) (GetUserByIdQueryRow, error) {
	row := q.db.QueryRow(ctx, getUserByIdQuery, id)
	var i GetUserByIdQueryRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserQuery = `-- name: UpdateUserQuery :exec

UPDATE users
SET username = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserQueryParams struct {
	Username string    `json:"username"`
	ID       uuid.UUID `json:"id"`
}

// -- name: GetTechs :many
// SELECT id, user_name, email, role, created_at, updated_at
// FROM users
// WHERE role = 'tecnico';
func (q *Queries) UpdateUserQuery(ctx context.Context, arg UpdateUserQueryParams) error {
	_, err := q.db.Exec(ctx, updateUserQuery, arg.Username, arg.ID)
	return err
}
